import { useEffect, useRef, useState } from "react";
import GridFloorPlanEditor from "./GridFloorPlanEditor";

const initialForm = {
  plotGaj: 200,
  plotShape: "rectangle",
  dwellingType: "house",
  bedrooms: 3,
  bathrooms: 2,
  frontDirection: "south",
  engine: "v1",
};

function App() {
  const [form, setForm] = useState(initialForm);
  const [plot, setPlot] = useState({
    plotWidth: 40,
    plotHeight: 50,
    plotGaj: initialForm.plotGaj,
    plotShape: initialForm.plotShape,
  });
  
  // New unified boundary state
  const [boundaries, setBoundaries] = useState({
    north: "covered",
    east: "open",
    south: "front", // derived from frontDirection
    west: "covered"
  });

  const [initialRooms, setInitialRooms] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [importJson, setImportJson] = useState("");
  const [showImport, setShowImport] = useState(false);
  const hasAutoGenerated = useRef(false);

  const handleChange = (event) => {
    const { name, value } = event.target;

    setForm((current) => {
      const updated = { ...current, [name]: value };
      
      // Auto-update boundaries when front direction changes
      if (name === "frontDirection") {
        setBoundaries(prev => {
          const nextBoundaries = { ...prev };
          // reset whatever was front before
          for (let key in nextBoundaries) {
            if (nextBoundaries[key] === "front") nextBoundaries[key] = "covered";
          }
          nextBoundaries[value] = "front"; // set new front
          return nextBoundaries;
        });
      }
      
      return updated;
    });
  };

  const handleBoundaryToggle = (direction) => {
    setBoundaries(prev => ({
      ...prev,
      [direction]: prev[direction] === "covered" ? "open" : "covered"
    }));
  };

  const requestLayout = async (nextPlot) => {
    setIsLoading(true);
    setError("");

    try {
      const response = await fetch("/api/layout", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ ...nextPlot, boundaries, engine: nextPlot.engine ?? "v1" }),
      });

      const payload = await response.json();

      if (!response.ok) {
        throw new Error(payload.error || "Failed to generate layout.");
      }

      setPlot({
        plotWidth: payload?.plot?.width ?? nextPlot.plotWidth,
        plotHeight: payload?.plot?.height ?? nextPlot.plotHeight,
        plotGaj: payload?.plot?.gaj ?? nextPlot.plotGaj,
        plotShape: payload?.plot?.shape ?? nextPlot.plotShape,
      });
      setInitialRooms(Array.isArray(payload?.rooms) ? payload.rooms : []);
    } catch (requestError) {
      setInitialRooms([]);
      setError(
        requestError instanceof TypeError
          ? "Could not reach the backend. Start the backend server and try again."
          : requestError.message,
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handleImportLayout = () => {
    if (!importJson.trim()) return;
    setError("");

    try {
      const payload = JSON.parse(importJson);
      
      if (!payload.plot || !payload.layout) {
        throw new Error("Invalid JSON format. Expected 'plot' and 'layout' keys.");
      }

      // 1. Update Plot
      setPlot({
        plotWidth: Number(payload.plot.width),
        plotHeight: Number(payload.plot.height),
        plotGaj: Number(payload.plot.gaj) || plot.plotGaj,
        plotShape: payload.plot.shape || plot.plotShape,
      });

      // 2. Update Boundaries if present
      if (payload.boundaries) {
        setBoundaries(payload.boundaries);
      }

      // 3. Update Form (Front Direction)
      if (payload.plot.front) {
        setForm(prev => ({ ...prev, frontDirection: payload.plot.front }));
      }

      // 4. Update Rooms
      // Ensure each room has the necessary fields
      const importedRooms = payload.layout.map(r => ({
        ...r,
        roomType: r.type || r.roomType,
        label: r.label || r.type || r.roomType,
        doors: r.doors || [],
        windows: r.windows || [],
      }));

      setInitialRooms(importedRooms);
      setImportJson("");
      setShowImport(false);
      
    } catch (err) {
      setError("Import Error: " + err.message);
    }
  };

  const handleSubmit = (event) => {
    event.preventDefault();

    requestLayout({
      plotGaj: Math.max(100, Math.min(400, Number(form.plotGaj) || initialForm.plotGaj)),
      plotShape: form.plotShape,
      dwellingType: form.dwellingType,
      bedrooms: Math.max(1, Math.min(6, Number(form.bedrooms) || initialForm.bedrooms)),
      bathrooms: Math.max(1, Math.min(4, Number(form.bathrooms) || initialForm.bathrooms)),
      frontDirection: form.frontDirection,
      engine: form.engine,
    });
  };

  useEffect(() => {
    if (hasAutoGenerated.current) return;
    hasAutoGenerated.current = true;

    requestLayout({
      plotGaj: initialForm.plotGaj,
      plotShape: initialForm.plotShape,
      dwellingType: initialForm.dwellingType,
      bedrooms: initialForm.bedrooms,
      bathrooms: initialForm.bathrooms,
      frontDirection: initialForm.frontDirection,
      engine: initialForm.engine,
    });
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <main className="app-shell">
      <section className="controls">
        <h1>Interactive Floor Plan Editor</h1>
        <p className="message">
          Choose the plot and room counts, generate the starting layout, then
          fine-tune it directly on the canvas.
        </p>

        <form onSubmit={handleSubmit}>
          <label>
            Plot Size (Gaj)
            <input
              max="400"
              min="100"
              name="plotGaj"
              onChange={handleChange}
              step="1"
              type="number"
              value={form.plotGaj}
            />
          </label>

          <label>
            Plot Shape
            <select name="plotShape" onChange={handleChange} value={form.plotShape}>
              <option value="square">Square</option>
              <option value="rectangle">Rectangle</option>
              <option value="deep-rectangle">Deep Rectangle</option>
            </select>
          </label>

          <label>
            Dwelling Type
            <select name="dwellingType" onChange={handleChange} value={form.dwellingType}>
              <option value="house">House</option>
              <option value="flat">Flat / Building Floor</option>
            </select>
          </label>

          <label>
            Bedrooms
            <input
              max="6"
              min="1"
              name="bedrooms"
              onChange={handleChange}
              step="1"
              type="number"
              value={form.bedrooms}
            />
          </label>

          <label>
            Bathrooms
            <input
              max="4"
              min="1"
              name="bathrooms"
              onChange={handleChange}
              step="1"
              type="number"
              value={form.bathrooms}
            />
          </label>

          <label>
            Front Direction
            <select name="frontDirection" onChange={handleChange} value={form.frontDirection}>
              <option value="north">North</option>
              <option value="east">East</option>
              <option value="south">South</option>
              <option value="west">West</option>
            </select>
          </label>
          
          <div className="boundary-toggles">
            <span className="boundary-toggles-label">Plot Boundaries</span>
            <p className="boundary-toggles-hint">Mark sides as blocked by neighbors or open for ventilation</p>
            {["north", "east", "south", "west"].map(dir => (
              boundaries[dir] !== "front" && (
                <button
                  key={dir}
                  type="button"
                  className={`boundary-toggle-btn ${boundaries[dir]}`}
                  onClick={() => handleBoundaryToggle(dir)}
                >
                  <span className="dir-label">{dir.charAt(0).toUpperCase() + dir.slice(1)} Side:</span>
                  <span className="status-label">
                    {boundaries[dir] === "covered" ? "🧱 Covered" : "🌬️ Open"}
                  </span>
                </button>
              )
            ))}
          </div>

          <div className="engine-toggle" style={{ marginTop: '1.5rem', padding: '1rem', background: '#eef2ff', border: '1px solid #c7d2fe', borderRadius: '4px' }}>
            <label style={{ display: 'flex', flexDirection: 'column', gap: '4px', margin: 0 }}>
              <strong>Layout Engine</strong>
              <select
                name="engine"
                value={form.engine}
                onChange={handleChange}
                style={{ padding: '6px 10px', borderRadius: '4px', border: '1px solid #c7d2fe' }}
              >
                <option value="v1">V1 — Rule-based (Stable)</option>
                <option value="v2">V2 — Smart Matrix (Beta)</option>
                <option value="v3">V3 — Smart Zoning (New)</option>
              </select>
            </label>
          </div>

          <button type="submit">Generate Layout</button>
        </form>

        <div className="import-container" style={{ marginTop: '1rem' }}>
          <button 
            type="button" 
            className="toggle-import-btn"
            onClick={() => setShowImport(!showImport)}
          >
            {showImport ? "🔼 Hide Import" : "🔧 Import Layout from JSON"}
          </button>
          
          {showImport && (
            <div className="import-content">
              <textarea
                className="import-textarea"
                placeholder="Paste your layout JSON here..."
                value={importJson}
                onChange={(e) => setImportJson(e.target.value)}
                rows={8}
              />
              <button 
                type="button" 
                className="apply-import-btn"
                onClick={handleImportLayout}
              >
                Apply Imported Layout
              </button>
            </div>
          )}
        </div>

        {isLoading ? <p className="message">Generating initial layout...</p> : null}
        {error ? <p className="message error">{error}</p> : null}

        <div className="spec-list">
          <p>Current plot: {plot.plotGaj ?? form.plotGaj} Gaj</p>
          <p>Shape: {plot.plotShape ?? form.plotShape}</p>
          <p>
            Footprint: {plot.plotWidth.toFixed(2)}ft × {plot.plotHeight.toFixed(2)}ft
          </p>
          <p>Drag rooms freely — they snap to the grid on release.</p>
        </div>
      </section>

      <section className="layout-panel">
        <GridFloorPlanEditor
          plotHeight={plot.plotHeight}
          plotWidth={plot.plotWidth}
          initialRooms={initialRooms}
          frontDirection={form.frontDirection}
          dwellingType={form.dwellingType}
          boundaries={boundaries}
        />
      </section>
    </main>
  );
}

export default App;
