import { useEffect, useRef, useState } from "react";
import GridFloorPlanEditor from "./GridFloorPlanEditor";

const initialForm = {
  plotGaj: 200,
  plotShape: "rectangle",
  dwellingType: "house",
  bedrooms: 3,
  bathrooms: 2,
  frontDirection: "south",
  engine: "v1",
};

const CARDINAL_DIRECTIONS = ["north", "east", "south", "west"];

function normalizeBoundaries(nextBoundaries, frontDirection) {
  const safeFrontDirection = CARDINAL_DIRECTIONS.includes(frontDirection)
    ? frontDirection
    : initialForm.frontDirection;
  const source = nextBoundaries && typeof nextBoundaries === "object" ? nextBoundaries : {};

  return CARDINAL_DIRECTIONS.reduce((acc, direction) => {
    if (direction === safeFrontDirection) {
      acc[direction] = "front";
    } else {
      acc[direction] = source[direction] === "open" ? "open" : "covered";
    }
    return acc;
  }, {});
}

function CustomSelect({ name, value, options, onChange, placeholder }) {
  const [isOpen, setIsOpen] = useState(false);
  const rootRef = useRef(null);

  useEffect(() => {
    if (!isOpen) return undefined;

    const closeOnOutsideClick = (event) => {
      if (rootRef.current && !rootRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    };

    document.addEventListener("pointerdown", closeOnOutsideClick);
    return () => document.removeEventListener("pointerdown", closeOnOutsideClick);
  }, [isOpen]);

  const selectedOption = options.find((option) => option.value === value);

  const handleTriggerKeyDown = (event) => {
    if (event.key === " " || event.key === "Enter" || event.key === "ArrowDown") {
      event.preventDefault();
      setIsOpen(true);
    }
    if (event.key === "Escape") {
      setIsOpen(false);
    }
  };

  return (
    <div className={`custom-select ${isOpen ? "open" : ""}`} ref={rootRef}>
      <button
        type="button"
        className="custom-select-trigger"
        aria-haspopup="listbox"
        aria-expanded={isOpen}
        onClick={() => setIsOpen((open) => !open)}
        onKeyDown={handleTriggerKeyDown}
      >
        <span>{selectedOption?.label ?? placeholder}</span>
        <span className="custom-select-chevron" aria-hidden="true" />
      </button>

      {isOpen ? (
        <div className="custom-select-menu" role="listbox" aria-label={name}>
          {options.map((option) => (
            <button
              key={option.value}
              type="button"
              className={`custom-select-option ${option.value === value ? "selected" : ""}`}
              role="option"
              aria-selected={option.value === value}
              onClick={() => {
                onChange(name, option.value);
                setIsOpen(false);
              }}
            >
              {option.label}
            </button>
          ))}
        </div>
      ) : null}
    </div>
  );
}

function App() {
  const [themeMode, setThemeMode] = useState(() => {
    if (typeof window === "undefined") return "light";
    const storedTheme = window.localStorage.getItem("floorplan-theme");
    return storedTheme === "dark" ? "dark" : "light";
  });
  const [form, setForm] = useState(initialForm);
  const [plot, setPlot] = useState({
    plotWidth: 40,
    plotHeight: 50,
    plotGaj: initialForm.plotGaj,
    plotShape: initialForm.plotShape,
  });
  
  // Unified boundary state with one canonical front side.
  const [boundaries, setBoundaries] = useState(() =>
    normalizeBoundaries(
      {
        north: "covered",
        east: "open",
        south: "front",
        west: "covered",
      },
      initialForm.frontDirection,
    ),
  );

  const [initialRooms, setInitialRooms] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [importJson, setImportJson] = useState("");
  const [showImport, setShowImport] = useState(false);
  const hasAutoGenerated = useRef(false);

  const handleChange = (event) => {
    const { name, value } = event.target;

    setForm((current) => {
      const updated = { ...current, [name]: value };
      
      // Keep boundaries canonical whenever front direction changes.
      if (name === "frontDirection") {
        setBoundaries((prev) => normalizeBoundaries(prev, value));
      }
      
      return updated;
    });
  };

  const handleBoundaryToggle = (direction) => {
    setBoundaries((prev) => {
      if (!CARDINAL_DIRECTIONS.includes(direction) || prev[direction] === "front") {
        return prev;
      }

      const nextStatus = prev[direction] === "covered" ? "open" : "covered";
      return normalizeBoundaries(
        {
          ...prev,
          [direction]: nextStatus,
        },
        form.frontDirection,
      );
    });
  };

  const handleSelectChange = (name, value) => {
    handleChange({ target: { name, value } });
  };

  const requestLayout = async (nextPlot) => {
    setIsLoading(true);
    setError("");

    try {
      const normalizedBoundaries = normalizeBoundaries(
        boundaries,
        nextPlot.frontDirection ?? form.frontDirection,
      );

      const response = await fetch("/api/layout", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          ...nextPlot,
          boundaries: normalizedBoundaries,
          engine: nextPlot.engine ?? "v1",
        }),
      });

      const payload = await response.json();

      if (!response.ok) {
        throw new Error(payload.error || "Failed to generate layout.");
      }

      setPlot({
        plotWidth: payload?.plot?.width ?? nextPlot.plotWidth,
        plotHeight: payload?.plot?.height ?? nextPlot.plotHeight,
        plotGaj: payload?.plot?.gaj ?? nextPlot.plotGaj,
        plotShape: payload?.plot?.shape ?? nextPlot.plotShape,
      });
      setInitialRooms(Array.isArray(payload?.rooms) ? payload.rooms : []);
    } catch (requestError) {
      setInitialRooms([]);
      setError(
        requestError instanceof TypeError
          ? "Could not reach the backend. Start the backend server and try again."
          : requestError.message,
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handleImportLayout = () => {
    if (!importJson.trim()) return;
    setError("");

    try {
      const payload = JSON.parse(importJson);
      
      if (!payload.plot || !payload.layout) {
        throw new Error("Invalid JSON format. Expected 'plot' and 'layout' keys.");
      }

      // 1. Update Plot
      setPlot({
        plotWidth: Number(payload.plot.width),
        plotHeight: Number(payload.plot.height),
        plotGaj: Number(payload.plot.gaj) || plot.plotGaj,
        plotShape: payload.plot.shape || plot.plotShape,
      });

      const requestedFrontDirection = payload?.plot?.front;
      const importedFrontDirection = CARDINAL_DIRECTIONS.includes(requestedFrontDirection)
        ? requestedFrontDirection
        : form.frontDirection;

      // 2. Update Form (Front Direction)
      if (requestedFrontDirection && CARDINAL_DIRECTIONS.includes(requestedFrontDirection)) {
        setForm((prev) => ({ ...prev, frontDirection: requestedFrontDirection }));
      }

      // 3. Update boundaries from import while enforcing one canonical front side.
      if (payload.boundaries || payload.plot.front) {
        setBoundaries((prev) =>
          normalizeBoundaries(payload.boundaries ?? prev, importedFrontDirection),
        );
      }

      // 4. Update Rooms
      // Ensure each room has the necessary fields
      const importedRooms = payload.layout.map(r => ({
        ...r,
        roomType: r.type || r.roomType,
        label: r.label || r.type || r.roomType,
        doors: r.doors || [],
        windows: r.windows || [],
      }));

      setInitialRooms(importedRooms);
      setImportJson("");
      setShowImport(false);
      
    } catch (err) {
      setError("Import Error: " + err.message);
    }
  };

  const handleSubmit = (event) => {
    event.preventDefault();

    requestLayout({
      plotGaj: Math.max(100, Math.min(400, Number(form.plotGaj) || initialForm.plotGaj)),
      plotShape: form.plotShape,
      dwellingType: form.dwellingType,
      bedrooms: Math.max(1, Math.min(6, Number(form.bedrooms) || initialForm.bedrooms)),
      bathrooms: Math.max(1, Math.min(4, Number(form.bathrooms) || initialForm.bathrooms)),
      frontDirection: form.frontDirection,
      engine: form.engine,
    });
  };

  useEffect(() => {
    if (hasAutoGenerated.current) return;
    hasAutoGenerated.current = true;

    requestLayout({
      plotGaj: initialForm.plotGaj,
      plotShape: initialForm.plotShape,
      dwellingType: initialForm.dwellingType,
      bedrooms: initialForm.bedrooms,
      bathrooms: initialForm.bathrooms,
      frontDirection: initialForm.frontDirection,
      engine: initialForm.engine,
    });
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (typeof window === "undefined") return;
    window.localStorage.setItem("floorplan-theme", themeMode);
  }, [themeMode]);

  return (
    <main className={`app-shell theme-${themeMode}`}>
      <section className="controls sidebar-shell">
        <div className="sidebar-project">
          <h2>Project Alpha</h2>
          <p>Residential Plan</p>
        </div>

        <div className="theme-switch" role="group" aria-label="Theme mode">
          <button
            type="button"
            className={`theme-btn ${themeMode === "light" ? "active" : ""}`}
            onClick={() => setThemeMode("light")}
          >
            Light
          </button>
          <button
            type="button"
            className={`theme-btn ${themeMode === "dark" ? "active" : ""}`}
            onClick={() => setThemeMode("dark")}
          >
            Dark
          </button>
        </div>

        <h1>Interactive Floor Plan Editor</h1>
        <p className="message">
          Choose the plot and room counts, generate the starting layout, then
          fine-tune it directly on the canvas.
        </p>

        <form onSubmit={handleSubmit} className="sidebar-form">
          <div className="sidebar-card">
            <h3 className="sidebar-card-title">Plot Configuration</h3>
            <label>
              Plot Size (Gaj)
              <input
                max="400"
                min="100"
                name="plotGaj"
                onChange={handleChange}
                step="1"
                type="number"
                value={form.plotGaj}
              />
            </label>

            <label>
              Plot Shape
              <CustomSelect
                name="plotShape"
                value={form.plotShape}
                onChange={handleSelectChange}
                options={[
                  { value: "square", label: "Square" },
                  { value: "rectangle", label: "Rectangle" },
                  { value: "deep-rectangle", label: "Deep Rectangle" },
                ]}
              />
            </label>

            <label>
              Front Direction
              <CustomSelect
                name="frontDirection"
                value={form.frontDirection}
                onChange={handleSelectChange}
                options={[
                  { value: "north", label: "North" },
                  { value: "east", label: "East" },
                  { value: "south", label: "South" },
                  { value: "west", label: "West" },
                ]}
              />
            </label>
          </div>

          <div className="sidebar-card">
            <h3 className="sidebar-card-title">Room Requirements</h3>
            <label>
              Dwelling Type
              <CustomSelect
                name="dwellingType"
                value={form.dwellingType}
                onChange={handleSelectChange}
                options={[
                  { value: "house", label: "House" },
                  { value: "flat", label: "Flat / Building Floor" },
                ]}
              />
            </label>

            <label>
              Bedrooms
              <input
                max="6"
                min="1"
                name="bedrooms"
                onChange={handleChange}
                step="1"
                type="number"
                value={form.bedrooms}
              />
            </label>

            <label>
              Bathrooms
              <input
                max="4"
                min="1"
                name="bathrooms"
                onChange={handleChange}
                step="1"
                type="number"
                value={form.bathrooms}
              />
            </label>
          </div>

          <div className="sidebar-card">
            <h3 className="sidebar-card-title">Plot Boundaries</h3>
            <div className="boundary-toggles">
              <p className="boundary-toggles-hint">Mark sides as blocked by neighbors or open for ventilation</p>
              <p className="boundary-front-note">
                Front side is controlled by Front Direction and remains locked.
              </p>
              {["north", "east", "south", "west"].map(dir => (
                boundaries[dir] !== "front" && (
                  <button
                    key={dir}
                    type="button"
                    className={`boundary-toggle-btn ${boundaries[dir]}`}
                    onClick={() => handleBoundaryToggle(dir)}
                  >
                    <span className="dir-label">{dir.charAt(0).toUpperCase() + dir.slice(1)} Side:</span>
                    <span className={`status-label ${boundaries[dir]}`}>
                      {boundaries[dir] === "covered" ? "Covered" : "Open"}
                    </span>
                  </button>
                )
              ))}
            </div>
          </div>

          <div className="sidebar-card engine-toggle">
            <h3 className="sidebar-card-title">Engine</h3>
            <label className="engine-toggle-label">
              <strong>Layout Engine</strong>
              <CustomSelect
                name="engine"
                value={form.engine}
                onChange={handleSelectChange}
                options={[
                  { value: "v1", label: "V1 - Rule-based (Stable)" },
                  { value: "v2", label: "V2 - Smart Matrix (Beta)" },
                  { value: "v3", label: "V3 - Smart Zoning (New)" },
                ]}
              />
            </label>
          </div>

          <button type="submit" className="sidebar-primary-cta">Generate Layout</button>
        </form>

        <div className="import-container sidebar-card sidebar-secondary-card">
          <h3 className="sidebar-card-title">Import / Export</h3>
          <button 
            type="button" 
            className="toggle-import-btn"
            onClick={() => setShowImport(!showImport)}
          >
            {showImport ? "🔼 Hide Import" : "🔧 Import Layout from JSON"}
          </button>
          
          {showImport && (
            <div className="import-content">
              <textarea
                className="import-textarea"
                placeholder="Paste your layout JSON here..."
                value={importJson}
                onChange={(e) => setImportJson(e.target.value)}
                rows={8}
              />
              <button 
                type="button" 
                className="apply-import-btn"
                onClick={handleImportLayout}
              >
                Apply Imported Layout
              </button>
            </div>
          )}
        </div>

        {isLoading ? <p className="message">Generating initial layout...</p> : null}
        {error ? <p className="message error">{error}</p> : null}

        <div className="spec-list sidebar-card sidebar-secondary-card sidebar-meta-card">
          <h3 className="sidebar-card-title">Current Plot</h3>
          <p>Current plot: {plot.plotGaj ?? form.plotGaj} Gaj</p>
          <p>Shape: {plot.plotShape ?? form.plotShape}</p>
          <p>
            Footprint: {plot.plotWidth.toFixed(2)}ft × {plot.plotHeight.toFixed(2)}ft
          </p>
          <p>Drag rooms freely — they snap to the grid on release.</p>
        </div>
      </section>

      <section className="layout-panel">
        <GridFloorPlanEditor
          plotHeight={plot.plotHeight}
          plotWidth={plot.plotWidth}
          initialRooms={initialRooms}
          frontDirection={form.frontDirection}
          dwellingType={form.dwellingType}
          boundaries={boundaries}
          themeMode={themeMode}
        />
      </section>
    </main>
  );
}

export default App;
